function myui

h = gcf;
pos= h.Position;

% n_row = r.dispClusterNum;
n_trace = 4;
n_row = 10;
n_col = n_trace + 2;
x0 = 0.2;
y0 = 0.0;
x_width = (1-x0)/n_col;
y_width = (1-y0)/n_row;
    

bg = uibuttongroup('Visible','off',...
                  'Position',[0 0 .1 1],...
                  'SelectionChangedFcn',@bselection);
              
% Create three radio buttons in the button group.
for i = 1:n_row
    str = ['Option ', num2str(i)];
%     uicontrol(bg,'Style',...
%                   'radiobutton',...
%                   'String', str,...
%                   'Position',[10 350-30*i 100 30],...
%                   'HandleVisibility','off',...
%                   'UserData', i);
              
              
              
                      uicontrol(bg,'Style',...
                  'radiobutton',...
                  'String', num2str(i),...
                  'Position', [0 ((1-y0)-i*y_width)*pos(4) x0*pos(3) y_width*pos(4)],...
                  'HandleVisibility','off',...
                  'UserData', i);      
end
    
    
    
    
    
% r1 = uicontrol(bg,'Style',...
%                   'radiobutton',...
%                   'String','Option 1',...
%                   'Position',[10 350 100 30],...
%                   'HandleVisibility','off');
%               
% r2 = uicontrol(bg,'Style','radiobutton',...
%                   'String','Option 2',...
%                   'Position',[10 250 100 30],...
%                   'HandleVisibility','off');
% 
% r3 = uicontrol(bg,'Style','radiobutton',...
%                   'String','Option 3',...
%                   'Position',[10 150 100 30],...
%                   'HandleVisibility','off');
              
% Make the uibuttongroup visible after creating child objects. 
bg.Visible = 'on';

    function bselection(source,event)
       display(['Previous: ' event.OldValue.String]);
       display(['Current: ' event.NewValue.String]);
       fprintf('%d', event.NewValue.UserData);
       display('------------------');
    end
end
