%myOMS();

newseed = OMS( 'DisplayRes', [1600, 900], 'DisplayRate', 60, ... 
            'movieDurationSecs', 300, ...
            'checkerSizeXum', 50, ...
            'checkerSizeYum', 50, ...
              'stimSizeXYum', 1600*[1 1], ...
              'recreation', 'no');

